name: Auto Release

on:
  push:
    tags:
      - 'v*'
      - 'testv*'

jobs:
  dummy-job:
    name: Dummy Job
    runs-on: ubuntu-latest

    steps:
      - name: Dummy Step
        run: echo "Dummy Step because I need at least one step without a condition"

  tagged-release:
    name: Tagged Release
    if: startsWith(github.ref, 'refs/tags/v')  # true release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Create Release
        uses: ncipollo/release-action@v1

  tagged-pre-release:
    name: Pre-release
    if: startsWith(github.ref, 'refs/tags/testv')  # pre-release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Create Pre-release
        uses: ncipollo/release-action@v1
        with:
          prerelease: true
